# Generated by Django 3.1.5 on 2021-01-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=2083)),
                ('Desired_Price', models.FloatField()),
                ('Email', models.EmailField(max_length=254)),
                ('Time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Amazon',
            },
        ),
    ]
