# Generated by Django 3.1.5 on 2021-01-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flipkart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=2083)),
                ('Desired_Price', models.FloatField()),
                ('Email', models.EmailField(max_length=254)),
                ('Time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'flipkart',
            },
        ),
        migrations.CreateModel(
            name='Snapdeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=2083)),
                ('Desired_Price', models.FloatField()),
                ('Email', models.EmailField(max_length=254)),
                ('Time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'snapdeal',
            },
        ),
        migrations.AlterModelOptions(
            name='amazon',
            options={'verbose_name_plural': 'amazon'},
        ),
        migrations.RemoveField(
            model_name='amazon',
            name='Time',
        ),
    ]
