# Generated by Django 3.1.5 on 2021-01-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker_app', '0003_auto_20210124_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flipkart',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
